### ISSUE TITLE
Any updates in the pipeline for this course? :)

### ISSUE THREAD

**Issue by chocobuckle** [ReactjsProgram/React-Native#2]
Hey Tyler, been subscribing to the website the last 2 months and worked my way though the Fundamentals, ES6, and Redux courses - all top quality stuff and they've been my #1 learning resource for React, but I've been a bit hesitant about diving into the Native course considering it's the oldest course on the site and pre React Router 4, Create React App, etc. Just wondering if there's an update planned at all? :)

**Comment by tylermcginnis** [comment]
Hey! There is an update coming. Probably a few months out though.
